# Generated by Django 6.0.3 on 2026-09-17 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(max_length=300)),
                ("streams", models.BigIntegerField()),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("share", models.DecimalField(decimal_places=4, max_digits=7)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("NGN", "NGN"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("master", "Master recording"),
                            ("mechanical", "Mechanical"),
                            ("performance", "Performance"),
                            ("neighbouring", "Neighbouring rights"),
                            ("sync", "Synchronisation"),
                            ("producer", "Producer or featured artist share"),
                            ("direct", "Direct sales and licensing"),
                        ],
                        default="master",
                        max_length=20,
                    ),
                ),
                (
                    "rate_source",
                    models.CharField(default="creator-supplied", max_length=200),
                ),
                ("rate_effective_date", models.DateField(blank=True, null=True)),
                ("rate_version", models.CharField(default="user-1", max_length=40)),
                (
                    "formula",
                    models.CharField(
                        default="streams * rate * share / 100", max_length=200
                    ),
                ),
                ("assumptions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("original_csv", models.BinaryField(blank=True, null=True)),
                ("schema_version", models.CharField(default="csv-1", max_length=20)),
                (
                    "processing_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="processed",
                        max_length=20,
                    ),
                ),
                ("row_fingerprint", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncomeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="royalty_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"), name="unique_user_source"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("track", models.CharField(max_length=500)),
                ("platform", models.CharField(max_length=300)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("NGN", "NGN"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                        ],
                        max_length=3,
                    ),
                ),
                ("work", models.CharField(blank=True, max_length=500)),
                ("recording_id", models.CharField(blank=True, max_length=120)),
                ("territory", models.CharField(blank=True, max_length=120)),
                ("usage_type", models.CharField(blank=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("master", "Master recording"),
                            ("mechanical", "Mechanical"),
                            ("performance", "Performance"),
                            ("neighbouring", "Neighbouring rights"),
                            ("sync", "Synchronisation"),
                            ("producer", "Producer or featured artist share"),
                            ("direct", "Direct sales and licensing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("units", models.BigIntegerField(blank=True, null=True)),
                (
                    "gross_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("payee", models.CharField(blank=True, max_length=300)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="royalties.statement",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "indexes": [
                    models.Index(
                        fields=["statement", "position"],
                        name="royalties_r_stateme_f1b1b5_idx",
                    )
                ],
            },
        ),
    ]
