# Generated by Django 6.0.3 on 2026-09-19 00:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("royalties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("raw", models.BinaryField()),
                ("digest", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("quarantined", "Waiting for scan"),
                            ("review", "Mapping review"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                        ],
                        default="quarantined",
                        max_length=20,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=500)),
                ("columns", models.JSONField(default=list)),
                ("extracted_rows", models.JSONField(default=list)),
                ("mapping", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batch",
                        to="royalties.statement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualIncome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=200)),
                ("work", models.CharField(blank=True, max_length=500)),
                ("platform", models.CharField(blank=True, max_length=200)),
                ("territory", models.CharField(blank=True, max_length=120)),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("master", "Master recording"),
                            ("mechanical", "Mechanical"),
                            ("performance", "Performance"),
                            ("neighbouring", "Neighbouring rights"),
                            ("sync", "Synchronisation"),
                            ("producer", "Producer or featured artist share"),
                            ("direct", "Direct sales and licensing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("NGN", "NGN"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("note", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_income",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MappingRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mapping", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="royalties.importbatch",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                fields=("owner", "digest"), name="unique_import_content"
            ),
        ),
    ]
