# Generated by Django 6.0.3 on 2026-09-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_emaildelivery_failed_at_emaildelivery_last_error"),
        ("royalties", "0002_importbatch_manualincome_mappingrevision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="original_artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statements",
                to="operations.privateartifact",
            ),
        ),
    ]
