# Generated by Django 6.0.3 on 2026-09-17 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("EP", "EP"),
                            ("Album", "Album"),
                        ],
                        default="Single",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("production", "Production"),
                            ("delivery", "Delivery"),
                            ("promotion", "Promotion"),
                            ("released", "Released"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("artwork", models.CharField(blank=True, max_length=300)),
                ("support_needs", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=2000)),
                ("done", models.BooleanField(default=False)),
                ("position", models.IntegerField(default=0)),
                ("assignee", models.CharField(blank=True, max_length=300)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="releases.releaseproject",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
