# Generated by Django 6.0.3 on 2026-09-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseproject",
            name="campaign_plan",
            field=models.TextField(blank=True, max_length=8000),
        ),
        migrations.AddField(
            model_name="releaseproject",
            name="metadata_ready",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="releaseproject",
            name="reminders_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
