# Generated by Django 6.0.8 on 2026-09-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_mark_legacy_samples"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaboration",
            name="budget_amount",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="budget_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "USD"),
                    ("NGN", "NGN"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                ],
                max_length=3,
            ),
        ),
    ]
