# Generated by Django 6.0.3 on 2026-09-19 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiteam", "0002_contextpreference_feedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("agent_id", models.CharField(max_length=40)),
                ("prompt", models.TextField()),
                (
                    "must_include",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Substrings the answer must contain.",
                    ),
                ),
                (
                    "must_not_include",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Substrings that fail the case.",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("passed", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("detail", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aiteam.evaluationcase",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="aiteam.evaluationrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.CharField(blank=True, max_length=40)),
                ("purpose", models.CharField(max_length=40)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("outcome", models.CharField(default="ok", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="aiteam_mode_created_a89712_idx"
                    )
                ],
            },
        ),
    ]
