# Generated by Django 6.0.3 on 2026-09-17 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("workspace_revision", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "accounts_user",
            },
        ),
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=300)),
                ("photo", models.CharField(blank=True, max_length=300)),
                ("role", models.CharField(default="Artist", max_length=300)),
                ("city", models.CharField(blank=True, max_length=300)),
                ("bio", models.TextField(blank=True, max_length=1000)),
                ("portfolio", models.CharField(blank=True, max_length=300)),
                ("genres", models.JSONField(blank=True, default=list)),
                ("goals", models.JSONField(blank=True, default=list)),
                ("city_public", models.BooleanField(default=True)),
                ("portfolio_public", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestLimit",
            fields=[
                (
                    "key",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("count", models.IntegerField(default=0)),
                ("expires", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires"], name="accounts_re_expires_11edff_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bytes", models.BinaryField()),
                ("byte_size", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="accounts_st_user_id_3b4774_idx")
                ],
            },
        ),
    ]
