# Generated by Django 6.0.3 on 2026-09-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_password"),
        ("operations", "0004_emaildelivery_failed_at_emaildelivery_last_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedimage",
            name="artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="operations.privateartifact",
            ),
        ),
        migrations.AlterField(
            model_name="storedimage",
            name="bytes",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
