# Generated by Django 6.0.3 on 2026-09-19 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_mutationreceipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(default="default", max_length=40, unique=True),
                ),
                (
                    "deletion_grace_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Hours between a deletion request and its execution.",
                    ),
                ),
                (
                    "shared_message_handling",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not decided"),
                            ("delete", "Delete messages this account sent"),
                            (
                                "retain_anonymised",
                                "Keep the text, remove the sender identity",
                            ),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "export_available_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How long a generated export stays downloadable. 0 disables exports.",
                    ),
                ),
                (
                    "audit_retention_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Days to keep audit records. 0 keeps them indefinitely.",
                    ),
                ),
                (
                    "notification_retention_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Days to keep read in-app notifications. 0 keeps them.",
                    ),
                ),
                (
                    "decision_reference",
                    models.CharField(
                        blank=True,
                        help_text="The approved LaunchDecision or document this policy comes from.",
                        max_length=200,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=200)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Retention policies",
                "permissions": [
                    ("approve_retentionpolicy", "Can approve retention policy")
                ],
            },
        ),
        migrations.CreateModel(
            name="PrivateArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("filename", models.CharField(max_length=200)),
                (
                    "content_type",
                    models.CharField(default="application/json", max_length=100),
                ),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(max_length=64)),
                ("encrypted", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="operations__expires_f5058b_idx"
                    )
                ],
            },
        ),
    ]
