# Generated by Django 6.0.3 on 2026-09-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0003_retentionpolicy_privateartifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildelivery",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="last_error",
            field=models.CharField(
                blank=True,
                help_text="Error type only, never message content.",
                max_length=200,
            ),
        ),
    ]
